FROM ruby:3.3.6
ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

RUN apt-get update -qq \
  && apt-get install -y build-essential libpq-dev vim git curl \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
# 作業ディレクトリを作成
RUN mkdir /app
WORKDIR /app

# Bundler をインストール
RUN gem install bundler

# アプリのコードをコピー
COPY . /app
